const extensionFileMapping = {
  1: { name: "Groff" },
  2: { name: "Groff" },
  3: { name: "Groff" },
  4: { name: "Groff" },
  5: { name: "Groff" },
  6: { name: "Groff" },
  7: { name: "Groff" },
  8: { name: "Groff" },
  9: { name: "Groff" },
  abap: { name: "ABAP" },
  asc: { name: "Public Key" },
  ash: { name: "AGS Script" },
  ampl: { name: "AMPL" },
  mod: { name: "XML" },
  g4: { name: "ANTLR" },
  apib: { name: "API Blueprint" },
  apl: { name: "APL" },
  dyalog: { name: "APL" },
  asp: { name: "ASP" },
  asax: { name: "ASP" },
  ascx: { name: "ASP" },
  ashx: { name: "ASP" },
  asmx: { name: "ASP" },
  aspx: { name: "ASP" },
  axd: { name: "ASP" },
  dats: { name: "ATS" },
  hats: { name: "ATS" },
  sats: { name: "ATS" },
  as: { name: "ActionScript" },
  adb: { name: "Ada" },
  ada: { name: "Ada" },
  ads: { name: "Ada" },
  agda: { name: "Agda" },
  als: { name: "Alloy" },
  apacheconf: { name: "ApacheConf" },
  vhost: { name: "Nginx" },
  cls: { name: "Visual Basic" },
  applescript: { name: "AppleScript" },
  scpt: { name: "AppleScript" },
  arc: { name: "Arc" },
  ino: { name: "Arduino" },
  asciidoc: { name: "AsciiDoc" },
  adoc: { name: "AsciiDoc" },
  aj: { name: "AspectJ" },
  asm: { name: "Assembly" },
  a51: { name: "Assembly" },
  inc: { name: "SourcePawn" },
  nasm: { name: "Assembly" },
  aug: { name: "Augeas" },
  ahk: { name: "AutoHotkey" },
  ahkl: { name: "AutoHotkey" },
  au3: { name: "AutoIt" },
  awk: { name: "Awk" },
  auk: { name: "Awk" },
  gawk: { name: "Awk" },
  mawk: { name: "Awk" },
  nawk: { name: "Awk" },
  bat: { name: "Batchfile" },
  cmd: { name: "Batchfile" },
  befunge: { name: "Befunge" },
  bison: { name: "Bison" },
  bb: { name: "BlitzBasic" },
  decls: { name: "BlitzBasic" },
  bmx: { name: "BlitzMax" },
  bsv: { name: "Bluespec" },
  boo: { name: "Boo" },
  b: { name: "Limbo" },
  bf: { name: "HyPhy" },
  brs: { name: "Brightscript" },
  bro: { name: "Bro" },
  c: { name: "C", class: "devicon-c-plain colored" },
  cats: { name: "C", class: "devicon-c-plain colored" },
  h: { name: "Objective-C" },
  idc: { name: "C", class: "devicon-c-plain colored" },
  w: { name: "C", class: "devicon-c-plain colored" },
  cs: { name: "C#", class: "devicon-csharp-plain colored" },
  cake: { name: "CoffeeScript" },
  cshtml: { name: "C#", class: "devicon-csharp-plain colored" },
  csx: { name: "C#", class: "devicon-csharp-plain colored" },
  cpp: { name: "C++", class: "devicon-cplusplus-plain colored" },
  "c++": { name: "C++", class: "devicon-cplusplus-plain colored" },
  cc: { name: "C++", class: "devicon-cplusplus-plain colored" },
  cp: { name: "Component Pascal" },
  cxx: { name: "C++", class: "devicon-cplusplus-plain colored" },
  "h++": { name: "C++", class: "devicon-cplusplus-plain colored" },
  hh: { name: "Hack" },
  hpp: { name: "C++", class: "devicon-cplusplus-plain colored" },
  hxx: { name: "C++", class: "devicon-cplusplus-plain colored" },
  inl: { name: "C++", class: "devicon-cplusplus-plain colored" },
  ipp: { name: "C++", class: "devicon-cplusplus-plain colored" },
  tcc: { name: "C++", class: "devicon-cplusplus-plain colored" },
  tpp: { name: "C++", class: "devicon-cplusplus-plain colored" },
  "c-objdump": { name: "C-ObjDump" },
  chs: { name: "C2hs Haskell" },
  clp: { name: "CLIPS" },
  cmake: { name: "CMake", class: "devicon-cmake-plain colored" },
  "cmake.in": { name: "CMake", class: "devicon-cmake-plain colored" },
  cob: { name: "COBOL" },
  cbl: { name: "COBOL" },
  ccp: { name: "COBOL" },
  cobol: { name: "COBOL" },
  cpy: { name: "COBOL" },
  css: { name: "CSS", class: "devicon-css3-plain colored" },
  csv: { name: "CSV" },
  capnp: { name: "Cap'n Proto" },
  mss: { name: "CartoCSS" },
  ceylon: { name: "Ceylon" },
  chpl: { name: "Chapel" },
  ch: { name: "xBase" },
  ck: { name: "ChucK" },
  cirru: { name: "Cirru" },
  clw: { name: "Clarion" },
  icl: { name: "Clean" },
  dcl: { name: "Clean" },
  click: { name: "Click" },
  clj: { name: "Clojure" },
  boot: { name: "Clojure" },
  cl2: { name: "Clojure" },
  cljc: { name: "Clojure" },
  cljs: { name: "Clojure" },
  "cljs.hl": { name: "Clojure" },
  cljscm: { name: "Clojure" },
  cljx: { name: "Clojure" },
  hic: { name: "Clojure" },
  coffee: { name: "CoffeeScript" },
  _coffee: { name: "CoffeeScript" },
  cjsx: { name: "CoffeeScript" },
  cson: { name: "CoffeeScript" },
  iced: { name: "CoffeeScript" },
  cfm: { name: "ColdFusion" },
  cfml: { name: "ColdFusion" },
  cfc: { name: "ColdFusion CFC" },
  lisp: { name: "NewLisp" },
  asd: { name: "Common Lisp" },
  cl: { name: "OpenCL" },
  l: { name: "PicoLisp" },
  lsp: { name: "NewLisp" },
  ny: { name: "Common Lisp" },
  podsl: { name: "Common Lisp" },
  sexp: { name: "Common Lisp" },
  cps: { name: "Component Pascal" },
  coq: { name: "Coq" },
  v: { name: "Verilog" },
  cppobjdump: { name: "Cpp-ObjDump" },
  "c++-objdump": { name: "Cpp-ObjDump" },
  "c++objdump": { name: "Cpp-ObjDump" },
  "cpp-objdump": { name: "Cpp-ObjDump" },
  "cxx-objdump": { name: "Cpp-ObjDump" },
  creole: { name: "Creole" },
  cr: { name: "Crystal" },
  feature: { name: "Cucumber" },
  cu: { name: "Cuda" },
  cuh: { name: "Cuda" },
  cy: { name: "Cycript" },
  pyx: { name: "Cython" },
  pxd: { name: "Cython" },
  pxi: { name: "Cython" },
  d: { name: "Makefile" },
  di: { name: "D" },
  "d-objdump": { name: "D-ObjDump" },
  com: { name: "DIGITAL Command Language" },
  dm: { name: "DM" },
  zone: { name: "DNS Zone" },
  arpa: { name: "DNS Zone" },
  darcspatch: { name: "Darcs Patch" },
  dpatch: { name: "Darcs Patch" },
  dart: { name: "Dart", class: "devicon-dart-plain colored" },
  diff: { name: "Diff" },
  patch: { name: "Diff" },
  dockerfile: { name: "Dockerfile", class: "devicon-docker-plain colored" },
  djs: { name: "Dogescript" },
  dylan: { name: "Dylan" },
  dyl: { name: "Dylan" },
  intr: { name: "Dylan" },
  lid: { name: "Dylan" },
  E: { name: "E" },
  ecl: { name: "ECLiPSe" },
  eclxml: { name: "ECL" },
  sch: { name: "KiCad" },
  brd: { name: "KiCad" },
  epj: { name: "Ecere Projects" },
  e: { name: "Eiffel" },
  ex: { name: "Elixir" },
  exs: { name: "Elixir" },
  elm: { name: "Elm" },
  el: { name: "Emacs Lisp" },
  emacs: { name: "Emacs Lisp" },
  "emacs.desktop": { name: "Emacs Lisp" },
  em: { name: "EmberScript" },
  emberscript: { name: "EmberScript" },
  erl: { name: "Erlang" },
  es: { name: "javascript", class: "devicon-javascript-plain colored" },
  escript: { name: "Erlang" },
  hrl: { name: "Erlang" },
  xrl: { name: "Erlang" },
  yrl: { name: "Erlang" },
  fs: { name: "GLSL" },
  fsi: { name: "F#" },
  fsx: { name: "F#" },
  fx: { name: "HLSL" },
  flux: { name: "FLUX" },
  f90: { name: "FORTRAN" },
  f: { name: "Forth" },
  f03: { name: "FORTRAN" },
  f08: { name: "FORTRAN" },
  f77: { name: "FORTRAN" },
  f95: { name: "FORTRAN" },
  for: { name: "Forth" },
  fpp: { name: "FORTRAN" },
  factor: { name: "Factor" },
  fy: { name: "Fancy" },
  fancypack: { name: "Fancy" },
  fan: { name: "Fantom" },
  "eam.fs": { name: "Formatted" },
  fth: { name: "Forth" },
  "4th": { name: "Forth" },
  forth: { name: "Forth" },
  fr: { name: "Text" },
  frt: { name: "Forth" },
  ftl: { name: "FreeMarker" },
  g: { name: "GAP" },
  gco: { name: "G-code" },
  gcode: { name: "G-code" },
  gms: { name: "GAMS" },
  gap: { name: "GAP" },
  gd: { name: "GDScript" },
  gi: { name: "GAP" },
  gitignore: { name: "gitignore", class: "devicon-git-plain colored" },
  tst: { name: "Scilab" },
  s: { name: "GAS" },
  ms: { name: "MAXScript" },
  glsl: { name: "GLSL" },
  fp: { name: "GLSL" },
  frag: { name: "javascript", class: "devicon-javascript-plain colored" },
  frg: { name: "GLSL" },
  fsh: { name: "GLSL" },
  fshader: { name: "GLSL" },
  geo: { name: "GLSL" },
  geom: { name: "GLSL" },
  glslv: { name: "GLSL" },
  gshader: { name: "GLSL" },
  shader: { name: "GLSL" },
  vert: { name: "GLSL" },
  vrx: { name: "GLSL" },
  vsh: { name: "GLSL" },
  vshader: { name: "GLSL" },
  gml: { name: "XML", class: "devicon-xml-plain colored" },
  kid: { name: "Genshi" },
  ebuild: { name: "Gentoo Ebuild" },
  eclass: { name: "Gentoo Eclass" },
  po: { name: "Gettext Catalog" },
  pot: { name: "Gettext Catalog" },
  glf: { name: "Glyph" },
  gp: { name: "Gnuplot" },
  gnu: { name: "Gnuplot" },
  gnuplot: { name: "Gnuplot" },
  plot: { name: "Gnuplot" },
  plt: { name: "Gnuplot" },
  go: { name: "Go", class: "devicon-go-plain colored" },
  golo: { name: "Golo" },
  gs: { name: "javascript", class: "devicon-javascript-plain colored" },
  gst: { name: "Gosu" },
  gsx: { name: "Gosu" },
  vark: { name: "Gosu" },
  grace: { name: "Grace" },
  gradle: { name: "Gradle", class: "devicon-gradle-original colored" },
  gf: { name: "Grammatical Framework" },
  graphql: { name: "GraphQL", class: "devicon-graphql-plain colored" },
  dot: { name: "Graphviz (DOT)" },
  gv: { name: "Graphviz (DOT)" },
  man: { name: "Groff" },
  "1in": { name: "Groff" },
  "1m": { name: "Groff" },
  "1x": { name: "Groff" },
  "3in": { name: "Groff" },
  "3m": { name: "Groff" },
  "3qt": { name: "Groff" },
  "3x": { name: "Groff" },
  me: { name: "Groff" },
  n: { name: "Nemerle" },
  rno: { name: "Groff" },
  roff: { name: "Groff" },
  groovy: { name: "Groovy", class: "devicon-groovy-plain colored" },
  grt: { name: "Groovy", class: "devicon-groovy-plain colored" },
  gtpl: { name: "Groovy", class: "devicon-groovy-plain colored" },
  gvy: { name: "Groovy", class: "devicon-groovy-plain colored" },
  gsp: { name: "Groovy Server Pages" },
  hcl: { name: "HCL" },
  tf: { name: "HCL" },
  hlsl: { name: "HLSL" },
  fxh: { name: "HLSL" },
  hlsli: { name: "HLSL" },
  html: { name: "html", class: "devicon-html5-plain colored" },
  htm: { name: "html", class: "devicon-html5-plain colored" },
  "html.hl": { name: "html", class: "devicon-html5-plain colored" },
  st: { name: "Smalltalk" },
  xht: { name: "html", class: "devicon-html5-plain colored" },
  xhtml: { name: "html", class: "devicon-html5-plain colored" },
  mustache: {
    name: "html+Django",
    class: "devicon-handlebars-original colored",
  },
  jinja: { name: "html+Django" },
  eex: { name: "html+EEX" },
  erb: { name: "html+ERB" },
  "erb.deface": { name: "html+ERB" },
  phtml: { name: "html+PHP" },
  http: { name: "HTTP" },
  php: { name: "php", class: "devicon-php-plain colored" },
  haml: { name: "Haml" },
  "haml.deface": { name: "Haml" },
  handlebars: {
    name: "Handlebars",
    class: "devicon-handlebars-original colored",
  },
  hbs: { name: "Handlebars", class: "devicon-handlebars-original colored" },
  hb: { name: "Harbour" },
  hs: { name: "Haskell" },
  hsc: { name: "Haskell" },
  hx: { name: "Haxe" },
  hxsl: { name: "Haxe" },
  hy: { name: "Hy" },
  pro: { name: "QMake" },
  dlm: { name: "IDL" },
  ipf: { name: "IGOR Pro" },
  ini: { name: "INI" },
  cfg: { name: "INI" },
  prefs: { name: "INI" },
  properties: { name: "INI" },
  irclog: { name: "IRC log" },
  weechatlog: { name: "IRC log" },
  idr: { name: "Idris" },
  lidr: { name: "Idris" },
  ni: { name: "Inform 7" },
  i7x: { name: "Inform 7" },
  iss: { name: "Inno Setup" },
  io: { name: "Io" },
  ik: { name: "Ioke" },
  thy: { name: "Isabelle" },
  ijs: { name: "J" },
  flex: { name: "JFlex" },
  jflex: { name: "JFlex" },
  json: { name: "json", class: "devicon-json-plain colored" },
  geojson: { name: "json", class: "devicon-json-plain colored" },
  lock: { name: "json", class: "devicon-json-plain colored" },
  topojson: { name: "json", class: "devicon-json-plain colored" },
  json5: { name: "JSON5" },
  jsonld: { name: "JSONLD" },
  jq: { name: "JSONiq" },
  jsx: { name: "jsx", class: "devicon-react-original colored" },
  jade: { name: "Jade" },
  j: { name: "Objective-J" },
  java: { name: "Java", class: "devicon-java-plain colored" },
  jsp: { name: "Java Server Pages" },
  js: { name: "javascript", class: "devicon-javascript-plain colored" },
  _js: { name: "javascript", class: "devicon-javascript-plain colored" },
  bones: { name: "javascript", class: "devicon-javascript-plain colored" },
  es6: { name: "javascript", class: "devicon-javascript-plain colored" },
  jake: { name: "javascript", class: "devicon-javascript-plain colored" },
  jsb: { name: "javascript", class: "devicon-javascript-plain colored" },
  jscad: { name: "javascript", class: "devicon-javascript-plain colored" },
  jsfl: { name: "javascript", class: "devicon-javascript-plain colored" },
  jsm: { name: "javascript", class: "devicon-javascript-plain colored" },
  jss: { name: "javascript", class: "devicon-javascript-plain colored" },
  njs: { name: "javascript", class: "devicon-javascript-plain colored" },
  pac: { name: "javascript", class: "devicon-javascript-plain colored" },
  sjs: { name: "javascript", class: "devicon-javascript-plain colored" },
  ssjs: { name: "javascript", class: "devicon-javascript-plain colored" },
  "sublime-build": {
    name: "javascript",
    class: "devicon-javascript-plain colored",
  },
  "sublime-commands": {
    name: "javascript",
    class: "devicon-javascript-plain colored",
  },
  "sublime-completions": {
    name: "javascript",
    class: "devicon-javascript-plain colored",
  },
  "sublime-keymap": {
    name: "javascript",
    class: "devicon-javascript-plain colored",
  },
  "sublime-macro": {
    name: "javascript",
    class: "devicon-javascript-plain colored",
  },
  "sublime-menu": {
    name: "javascript",
    class: "devicon-javascript-plain colored",
  },
  "sublime-mousemap": {
    name: "javascript",
    class: "devicon-javascript-plain colored",
  },
  "sublime-project": {
    name: "javascript",
    class: "devicon-javascript-plain colored",
  },
  "sublime-settings": {
    name: "javascript",
    class: "devicon-javascript-plain colored",
  },
  "sublime-theme": {
    name: "javascript",
    class: "devicon-javascript-plain colored",
  },
  "sublime-workspace": {
    name: "javascript",
    class: "devicon-javascript-plain colored",
  },
  sublime_metrics: {
    name: "javascript",
    class: "devicon-javascript-plain colored",
  },
  sublime_session: {
    name: "javascript",
    class: "devicon-javascript-plain colored",
  },
  xsjs: { name: "javascript", class: "devicon-javascript-plain colored" },
  xsjslib: { name: "javascript", class: "devicon-javascript-plain colored" },
  jl: { name: "Julia" },
  ipynb: { name: "Jupyter Notebook", class: "devicon-jupyter-plain colored" },
  krl: { name: "KRL" },
  kicad_pcb: { name: "KiCad" },
  kit: { name: "Kit" },
  kt: { name: "Kotlin", class: "devicon-kotlin-plain colored" },
  ktm: { name: "Kotlin", class: "devicon-kotlin-plain colored" },
  kts: { name: "Kotlin", class: "devicon-kotlin-plain colored" },
  lfe: { name: "LFE" },
  ll: { name: "LLVM" },
  lol: { name: "LOLCODE" },
  lsl: { name: "LSL" },
  lslp: { name: "LSL" },
  lvproj: { name: "LabVIEW" },
  lasso: { name: "Lasso" },
  las: { name: "Lasso" },
  lasso8: { name: "Lasso" },
  lasso9: { name: "Lasso" },
  ldml: { name: "Lasso" },
  latte: { name: "Latte" },
  lean: { name: "Lean" },
  hlean: { name: "Lean" },
  less: { name: "less" },
  lex: { name: "Lex" },
  ly: { name: "LilyPond" },
  ily: { name: "LilyPond" },
  m: { name: "Objective-C" },
  ld: { name: "Linker Script" },
  lds: { name: "Linker Script" },
  liquid: { name: "Liquid" },
  lagda: { name: "Literate Agda" },
  litcoffee: { name: "Literate CoffeeScript" },
  lhs: { name: "Literate Haskell" },
  ls: { name: "LoomScript" },
  _ls: { name: "LiveScript" },
  xm: { name: "Logos" },
  x: { name: "Logos" },
  xi: { name: "Logos" },
  lgt: { name: "Logtalk" },
  logtalk: { name: "Logtalk" },
  lookml: { name: "LookML" },
  lua: { name: "Lua", class: "devicon-lua-plain colored" },
  fcgi: { name: "Shell" },
  nse: { name: "Lua", class: "devicon-lua-plain colored" },
  pd_lua: { name: "Lua", class: "devicon-lua-plain colored" },
  rbxs: { name: "Lua", class: "devicon-lua-plain colored" },
  wlua: { name: "Lua", class: "devicon-lua-plain colored" },
  mumps: { name: "M" },
  m4: { name: "M4Sugar" },
  mcr: { name: "MAXScript" },
  mtml: { name: "MTML" },
  muf: { name: "MUF" },
  mak: { name: "Makefile" },
  mk: { name: "Makefile" },
  mkfile: { name: "Makefile" },
  mako: { name: "Mako" },
  mao: { name: "Mako" },
  md: { name: "Markdown" },
  markdown: { name: "Markdown" },
  mkd: { name: "Markdown" },
  mkdn: { name: "Markdown" },
  mkdown: { name: "Markdown" },
  ron: { name: "Markdown" },
  mask: { name: "Mask" },
  mathematica: { name: "Mathematica" },
  cdf: { name: "Mathematica" },
  ma: { name: "Mathematica" },
  mt: { name: "Mathematica" },
  nb: { name: "Text" },
  nbp: { name: "Mathematica" },
  wl: { name: "Mathematica" },
  wlt: { name: "Mathematica" },
  matlab: { name: "Matlab" },
  maxpat: { name: "Max" },
  maxhelp: { name: "Max" },
  maxproj: { name: "Max" },
  mxt: { name: "Max" },
  pat: { name: "Max" },
  mediawiki: { name: "MediaWiki" },
  wiki: { name: "MediaWiki" },
  moo: { name: "Moocode" },
  metal: { name: "Metal" },
  minid: { name: "MiniD" },
  druby: { name: "Mirah" },
  duby: { name: "Mirah" },
  mir: { name: "Mirah" },
  mirah: { name: "Mirah" },
  mo: { name: "Modelica" },
  mms: { name: "Module Management System" },
  mmk: { name: "Module Management System" },
  monkey: { name: "Monkey" },
  moon: { name: "MoonScript" },
  myt: { name: "Myghty" },
  ncl: { name: "Text" },
  nl: { name: "NewLisp" },
  nsi: { name: "NSIS" },
  nsh: { name: "NSIS" },
  axs: { name: "NetLinx" },
  axi: { name: "NetLinx" },
  "axs.erb": { name: "NetLinx+ERB" },
  "axi.erb": { name: "NetLinx+ERB" },
  nlogo: { name: "NetLogo" },
  nginxconf: { name: "Nginx" },
  nim: { name: "Nimrod" },
  nimrod: { name: "Nimrod" },
  ninja: { name: "Ninja" },
  nit: { name: "Nit" },
  nix: { name: "Nix" },
  nu: { name: "Nu" },
  numpy: { name: "NumPy" },
  numpyw: { name: "NumPy" },
  numsc: { name: "NumPy" },
  ml: { name: "OCaml" },
  eliom: { name: "OCaml" },
  eliomi: { name: "OCaml" },
  ml4: { name: "OCaml" },
  mli: { name: "OCaml" },
  mll: { name: "OCaml" },
  mly: { name: "OCaml" },
  objdump: { name: "ObjDump" },
  mm: { name: "xml" },
  sj: { name: "Objective-J" },
  omgrofl: { name: "Omgrofl" },
  opa: { name: "Opa" },
  opal: { name: "Opal" },
  opencl: { name: "OpenCL" },
  p: { name: "OpenEdge ABL" },
  scad: { name: "OpenSCAD" },
  org: { name: "Org" },
  ox: { name: "Ox" },
  oxh: { name: "Ox" },
  oxo: { name: "Ox" },
  oxygene: { name: "Oxygene" },
  oz: { name: "Oz" },
  pwn: { name: "PAWN" },
  aw: { name: "php", class: "devicon-php-plain colored" },
  ctp: { name: "php", class: "devicon-php-plain colored" },
  php3: { name: "php", class: "devicon-php-plain colored" },
  php4: { name: "php", class: "devicon-php-plain colored" },
  php5: { name: "php", class: "devicon-php-plain colored" },
  phps: { name: "php", class: "devicon-php-plain colored" },
  phpt: { name: "php", class: "devicon-php-plain colored" },
  pls: { name: "PLSQL" },
  pck: { name: "PLSQL" },
  pkb: { name: "PLSQL" },
  pks: { name: "PLSQL" },
  plb: { name: "PLSQL" },
  plsql: { name: "PLSQL" },
  sql: { name: "SQLPL", class: "devicon-azuresqldatabase-plain colored" },
  pov: { name: "POV-Ray SDL" },
  pan: { name: "Pan" },
  psc: { name: "Papyrus" },
  parrot: { name: "Parrot" },
  pasm: { name: "Parrot Assembly" },
  pir: { name: "Parrot Internal Representation" },
  pas: { name: "Pascal" },
  dfm: { name: "Pascal" },
  dpr: { name: "Pascal" },
  lpr: { name: "Pascal" },
  pp: { name: "Puppet" },
  pl: { name: "Prolog" },
  al: { name: "Perl", class: "devicon-perl-plain colored" },
  cgi: { name: "Shell" },
  perl: { name: "Perl", class: "devicon-perl-plain colored" },
  ph: { name: "Perl", class: "devicon-perl-plain colored" },
  plx: { name: "Perl", class: "devicon-perl-plain colored" },
  pm: { name: "Perl6" },
  pod: { name: "Pod" },
  psgi: { name: "Perl", class: "devicon-perl-plain colored" },
  t: { name: "Turing" },
  "6pl": { name: "Perl6" },
  "6pm": { name: "Perl6" },
  nqp: { name: "Perl6" },
  p6: { name: "Perl6" },
  p6l: { name: "Perl6" },
  p6m: { name: "Perl6" },
  pl6: { name: "Perl6" },
  pm6: { name: "Perl6" },
  pkl: { name: "Pickle" },
  pig: { name: "PigLatin" },
  pike: { name: "Pike" },
  pmod: { name: "Pike" },
  pogo: { name: "PogoScript" },
  pony: { name: "Pony" },
  ps: { name: "PostScript" },
  eps: { name: "PostScript" },
  ps1: { name: "PowerShell", class: "devicon-powershell-plain colored" },
  psd1: { name: "PowerShell", class: "devicon-powershell-plain colored" },
  psm1: { name: "PowerShell", class: "devicon-powershell-plain colored" },
  pde: { name: "Processing" },
  prolog: { name: "Prolog" },
  yap: { name: "Prolog" },
  spin: { name: "Propeller Spin" },
  proto: { name: "Protocol Buffer" },
  pub: { name: "Public Key" },
  pd: { name: "Pure Data" },
  pb: { name: "PureBasic" },
  pbi: { name: "PureBasic" },
  purs: { name: "PureScript" },
  py: { name: "python", class: "devicon-python-plain colored" },
  bzl: { name: "python", class: "devicon-python-plain colored" },
  gyp: { name: "python", class: "devicon-python-plain colored" },
  lmi: { name: "python", class: "devicon-python-plain colored" },
  pyde: { name: "python", class: "devicon-python-plain colored" },
  pyp: { name: "python", class: "devicon-python-plain colored" },
  pyt: { name: "python", class: "devicon-python-plain colored" },
  pyw: { name: "python", class: "devicon-python-plain colored" },
  rpy: { name: "Ren'Py" },
  tac: { name: "python", class: "devicon-python-plain colored" },
  wsgi: { name: "python", class: "devicon-python-plain colored" },
  xpy: { name: "python", class: "devicon-python-plain colored" },
  pytb: { name: "Python traceback" },
  qml: { name: "QML" },
  qbs: { name: "QML" },
  pri: { name: "QMake" },
  r: { name: "Rebol", class: "devicon-r-plain colored" },
  rd: { name: "R" },
  rsx: { name: "R" },
  raml: { name: "RAML" },
  rdoc: { name: "RDoc" },
  rbbas: { name: "REALbasic" },
  rbfrm: { name: "REALbasic" },
  rbmnu: { name: "REALbasic" },
  rbres: { name: "REALbasic" },
  rbtbar: { name: "REALbasic" },
  rbuistate: { name: "REALbasic" },
  rhtml: { name: "RHTML" },
  rmd: { name: "RMarkdown" },
  rkt: { name: "Racket" },
  rktd: { name: "Racket" },
  rktl: { name: "Racket" },
  scrbl: { name: "Racket" },
  rl: { name: "Ragel in Ruby Host" },
  raw: { name: "Raw token data" },
  reb: { name: "Rebol" },
  r2: { name: "Rebol" },
  r3: { name: "Rebol" },
  rebol: { name: "Rebol" },
  red: { name: "Red" },
  reds: { name: "Red" },
  cw: { name: "Redcode" },
  rs: { name: "Rust", class: "devicon-rust-original colored" },
  rsh: { name: "RenderScript" },
  robot: { name: "RobotFramework" },
  rg: { name: "Rouge" },
  rb: { name: "Ruby", class: "devicon-ruby-plain colored" },
  builder: { name: "Ruby", class: "devicon-ruby-plain colored" },
  gemspec: { name: "Ruby", class: "devicon-ruby-plain colored" },
  god: { name: "Ruby", class: "devicon-ruby-plain colored" },
  irbrc: { name: "Ruby", class: "devicon-ruby-plain colored" },
  jbuilder: { name: "Ruby", class: "devicon-ruby-plain colored" },
  mspec: { name: "Ruby", class: "devicon-ruby-plain colored" },
  pluginspec: { name: "XML" },
  podspec: { name: "Ruby", class: "devicon-ruby-plain colored" },
  rabl: { name: "Ruby", class: "devicon-ruby-plain colored" },
  rake: { name: "Ruby", class: "devicon-ruby-plain colored" },
  rbuild: { name: "Ruby", class: "devicon-ruby-plain colored" },
  rbw: { name: "Ruby", class: "devicon-ruby-plain colored" },
  rbx: { name: "Ruby", class: "devicon-ruby-plain colored" },
  ru: { name: "Ruby", class: "devicon-ruby-plain colored" },
  ruby: { name: "Ruby", class: "devicon-ruby-plain colored" },
  thor: { name: "Ruby", class: "devicon-ruby-plain colored" },
  watchr: { name: "Ruby", class: "devicon-ruby-plain colored" },
  "rs.in": { name: "Rust" },
  sas: { name: "SAS" },
  scss: { name: "scss" },
  smt2: { name: "SMT" },
  smt: { name: "SMT" },
  sparql: { name: "SPARQL" },
  rq: { name: "SPARQL" },
  sqf: { name: "SQF" },
  hqf: { name: "SQF" },
  cql: { name: "SQL" },
  ddl: { name: "SQL" },
  prc: { name: "SQL" },
  tab: { name: "SQL" },
  udf: { name: "SQL" },
  viw: { name: "SQL" },
  db2: { name: "SQLPL" },
  ston: { name: "STON" },
  svg: { name: "SVG" },
  sage: { name: "Sage" },
  sagews: { name: "Sage" },
  sls: { name: "Scheme" },
  sass: { name: "Sass", class: "devicon-sass-original colored" },
  scala: { name: "Scala" },
  sbt: { name: "Scala" },
  sc: { name: "SuperCollider" },
  scaml: { name: "Scaml" },
  scm: { name: "Scheme" },
  sld: { name: "Scheme" },
  sps: { name: "Scheme" },
  ss: { name: "Scheme" },
  sci: { name: "Scilab" },
  sce: { name: "Scilab" },
  self: { name: "Self" },
  sh: { name: "Shell" },
  bash: { name: "Shell", class: "devicon-bash-plain colored" },
  bats: { name: "Shell" },
  command: { name: "Shell" },
  ksh: { name: "Shell" },
  "sh.in": { name: "Shell" },
  tmux: { name: "Shell" },
  tool: { name: "Shell" },
  zsh: { name: "Shell" },
  "sh-session": { name: "ShellSession" },
  shen: { name: "Shen" },
  sl: { name: "Slash" },
  slim: { name: "Slim" },
  smali: { name: "Smali" },
  tpl: { name: "Smarty" },
  sp: { name: "SourcePawn" },
  sma: { name: "SourcePawn" },
  nut: { name: "Squirrel" },
  stan: { name: "Stan" },
  ML: { name: "Standard ML" },
  fun: { name: "Standard ML" },
  sig: { name: "Standard ML" },
  sml: { name: "Standard ML" },
  do: { name: "Stata" },
  ado: { name: "Stata" },
  doh: { name: "Stata" },
  ihlp: { name: "Stata" },
  mata: { name: "Stata" },
  matah: { name: "Stata" },
  sthlp: { name: "Stata" },
  styl: { name: "Stylus" },
  scd: { name: "SuperCollider" },
  swift: { name: "Swift" },
  sv: { name: "SystemVerilog" },
  svh: { name: "SystemVerilog" },
  vh: { name: "SystemVerilog" },
  toml: { name: "TOML" },
  txl: { name: "TXL" },
  tcl: { name: "Tcl" },
  adp: { name: "Tcl" },
  tm: { name: "Tcl" },
  tcsh: { name: "Tcsh" },
  csh: { name: "Tcsh" },
  tex: { name: "TeX" },
  aux: { name: "TeX" },
  bbx: { name: "TeX" },
  bib: { name: "TeX" },
  cbx: { name: "TeX" },
  dtx: { name: "TeX" },
  ins: { name: "TeX" },
  lbx: { name: "TeX" },
  ltx: { name: "TeX" },
  mkii: { name: "TeX" },
  mkiv: { name: "TeX" },
  mkvi: { name: "TeX" },
  sty: { name: "TeX" },
  toc: { name: "TeX" },
  tea: { name: "Tea" },
  txt: { name: "Text" },
  no: { name: "Text" },
  textile: { name: "Textile" },
  thrift: { name: "Thrift" },
  tu: { name: "Turing" },
  ttl: { name: "Turtle" },
  twig: { name: "Twig" },
  ts: { name: "typescript", class: "devicon-typescript-plain colored" },
  tsx: { name: "typescriptreact", class: "devicon-react-original colored" },
  upc: { name: "Unified Parallel C" },
  anim: { name: "Unity3D Asset", class: "devicon-unity-plain colored" },
  asset: { name: "Unity3D Asset", class: "devicon-unity-plain colored" },
  mat: { name: "Unity3D Asset", class: "devicon-unity-plain colored" },
  meta: { name: "Unity3D Asset", class: "devicon-unity-plain colored" },
  prefab: { name: "Unity3D Asset", class: "devicon-unity-plain colored" },
  unity: { name: "Unity3D Asset", class: "devicon-unity-plain colored" },
  uno: { name: "Uno" },
  uc: { name: "UnrealScript" },
  ur: { name: "UrWeb" },
  urs: { name: "UrWeb" },
  vcl: { name: "VCL" },
  vhdl: { name: "VHDL" },
  vhd: { name: "VHDL" },
  vhf: { name: "VHDL" },
  vhi: { name: "VHDL" },
  vho: { name: "VHDL" },
  vhs: { name: "VHDL" },
  vht: { name: "VHDL" },
  vhw: { name: "VHDL" },
  vala: { name: "Vala" },
  vapi: { name: "Vala" },
  veo: { name: "Verilog" },
  vim: { name: "VimL" },
  vb: { name: "Visual Basic", class: "devicon-visualbasic-plain colored" },
  bas: { name: "Visual Basic", class: "devicon-visualbasic-plain colored" },
  frm: { name: "Visual Basic", class: "devicon-visualbasic-plain colored" },
  frx: { name: "Visual Basic", class: "devicon-visualbasic-plain colored" },
  vba: { name: "Visual Basic", class: "devicon-visualbasic-plain colored" },
  vbhtml: { name: "Visual Basic", class: "devicon-visualbasic-plain colored" },
  vbs: { name: "Visual Basic", class: "devicon-visualbasic-plain colored" },
  volt: { name: "Volt" },
  vue: { name: "Vue" },
  owl: { name: "Web Ontology Language" },
  webidl: { name: "WebIDL" },
  x10: { name: "X10" },
  xc: { name: "XC" },
  xml: { name: "XML" },
  ant: { name: "XML" },
  axml: { name: "XML" },
  ccxml: { name: "XML" },
  clixml: { name: "XML" },
  cproject: { name: "XML" },
  csl: { name: "XML" },
  csproj: { name: "XML" },
  ct: { name: "XML" },
  dita: { name: "XML" },
  ditamap: { name: "XML" },
  ditaval: { name: "XML" },
  "dll.config": { name: "XML" },
  dotsettings: { name: "XML" },
  filters: { name: "XML" },
  fsproj: { name: "XML" },
  fxml: { name: "XML" },
  glade: { name: "XML" },
  grxml: { name: "XML" },
  iml: { name: "XML" },
  ivy: { name: "XML" },
  jelly: { name: "XML" },
  jsproj: { name: "XML" },
  kml: { name: "XML" },
  launch: { name: "XML" },
  mdpolicy: { name: "XML" },
  mxml: { name: "XML" },
  nproj: { name: "XML" },
  nuspec: { name: "XML" },
  odd: { name: "XML" },
  osm: { name: "XML" },
  plist: { name: "XML" },
  props: { name: "XML" },
  ps1xml: { name: "XML" },
  psc1: { name: "XML" },
  pt: { name: "XML" },
  rdf: { name: "XML" },
  rss: { name: "XML" },
  scxml: { name: "XML" },
  srdf: { name: "XML" },
  storyboard: { name: "XML" },
  stTheme: { name: "XML" },
  "sublime-snippet": { name: "XML" },
  targets: { name: "XML" },
  tmCommand: { name: "XML" },
  tml: { name: "XML" },
  tmLanguage: { name: "XML" },
  tmPreferences: { name: "XML" },
  tmSnippet: { name: "XML" },
  tmTheme: { name: "XML" },
  ui: { name: "XML" },
  urdf: { name: "XML" },
  ux: { name: "XML" },
  vbproj: { name: "XML" },
  vcxproj: { name: "XML" },
  vssettings: { name: "XML" },
  vxml: { name: "XML" },
  wsdl: { name: "XML" },
  wsf: { name: "XML" },
  wxi: { name: "XML" },
  wxl: { name: "XML" },
  wxs: { name: "XML" },
  x3d: { name: "XML" },
  xacro: { name: "XML" },
  xaml: { name: "XML" },
  xib: { name: "XML" },
  xlf: { name: "XML" },
  xliff: { name: "XML" },
  xmi: { name: "XML" },
  "xml.dist": { name: "XML" },
  xproj: { name: "XML" },
  xsd: { name: "XML" },
  xul: { name: "XML" },
  zcml: { name: "XML" },
  "xsp-config": { name: "XPages" },
  "xsp.metadata": { name: "XPages" },
  xpl: { name: "XProc" },
  xproc: { name: "XProc" },
  xquery: { name: "XQuery" },
  xq: { name: "XQuery" },
  xql: { name: "XQuery" },
  xqm: { name: "XQuery" },
  xqy: { name: "XQuery" },
  xs: { name: "XS" },
  xslt: { name: "XSLT" },
  xsl: { name: "XSLT" },
  xojo_code: { name: "Xojo" },
  xojo_menu: { name: "Xojo" },
  xojo_report: { name: "Xojo" },
  xojo_script: { name: "Xojo" },
  xojo_toolbar: { name: "Xojo" },
  xojo_window: { name: "Xojo" },
  xtend: { name: "Xtend" },
  yml: { name: "YAML" },
  reek: { name: "YAML" },
  rviz: { name: "YAML" },
  "sublime-syntax": { name: "YAML" },
  syntax: { name: "YAML" },
  yaml: { name: "YAML" },
  "yaml-tmlanguage": { name: "YAML" },
  yang: { name: "YANG" },
  y: { name: "Yacc" },
  yacc: { name: "Yacc" },
  yy: { name: "Yacc" },
  zep: { name: "Zephir" },
  zimpl: { name: "Zimpl" },
  zmpl: { name: "Zimpl" },
  zpl: { name: "Zimpl" },
  desktop: { name: "desktop" },
  "desktop.in": { name: "desktop" },
  ec: { name: "eC" },
  eh: { name: "eC" },
  edn: { name: "edn" },
  fish: { name: "fish" },
  mu: { name: "mupad" },
  nc: { name: "nesC" },
  ooc: { name: "ooc" },
  rst: { name: "reStructuredText" },
  rest: { name: "reStructuredText" },
  "rest.txt": { name: "reStructuredText" },
  "rst.txt": { name: "reStructuredText" },
  wisp: { name: "wisp" },
  prg: { name: "xBase" },
  prw: { name: "xBase" },
};

export default extensionFileMapping;
